export const environmentList = [
  {
    _id: '1',
    name: 'Forest',
    imageUrl: 'https://azurefunctionsapp2022060.blob.core.windows.net/cyoa/forest_1.jpg',
    prompt: 'a dense, mysterious forest with towering trees and hidden paths',
  },
  {
    _id: '2',
    name: 'Desert',
    imageUrl: 'https://azurefunctionsapp2022060.blob.core.windows.net/cyoa/desert_2.jpg',
    prompt: 'a vast, scorching desert with endless dunes and rare oases',
  },
  {
    _id: '3',
    name: 'Mountain',
    imageUrl: 'https://azurefunctionsapp2022060.blob.core.windows.net/cyoa/mountain_3.jpg',
    prompt: 'a rugged mountain range with steep cliffs and snowy peaks',
  },
  {
    _id: '4',
    name: 'Ocean',
    imageUrl: 'https://azurefunctionsapp2022060.blob.core.windows.net/cyoa/ocean_4.jpg',
    prompt: 'a deep, uncharted ocean with coral reefs and sunken ships',
  },
  {
    _id: '5',
    name: 'City',
    imageUrl: 'https://azurefunctionsapp2022060.blob.core.windows.net/cyoa/city_5.jpg',
    prompt: 'a bustling modern city with skyscrapers and neon lights',
  },
  {
    _id: '6',
    name: 'Space Station',
    imageUrl: 'https://azurefunctionsapp2022060.blob.core.windows.net/cyoa/spacestation_6.jpg',
    prompt: 'a high-tech space station orbiting a distant planet',
  },
  {
    _id: '7',
    name: 'Medieval Village',
    imageUrl: 'https://azurefunctionsapp2022060.blob.core.windows.net/cyoa/medievalvillage_7.jpg',
    prompt: 'a quaint medieval village with cobblestone streets and thatched roofs',
  },
  {
    _id: '8',
    name: 'Jungle',
    imageUrl: 'https://azurefunctionsapp2022060.blob.core.windows.net/cyoa/jungle_8.jpg',
    prompt: 'a dense jungle teeming with wildlife and ancient ruins',
  },
  {
    _id: '9',
    name: 'Arctic Tundra',
    imageUrl: 'https://azurefunctionsapp2022060.blob.core.windows.net/cyoa/arctic_9.jpg',
    prompt: 'a frozen arctic tundra with icy plains and howling winds',
  },
  {
    _id: '10',
    name: 'Haunted Mansion',
    imageUrl: 'https://azurefunctionsapp2022060.blob.core.windows.net/cyoa/spookymansion_10.jpg',
    prompt: 'a creepy, abandoned mansion filled with ghostly secrets',
  },
  {
    _id: '11',
    name: 'Underground Cave',
    imageUrl: 'https://azurefunctionsapp2022060.blob.core.windows.net/cyoa/cave_11.jpg',
    prompt: 'a sprawling underground cave system with glowing crystals',
  },
  {
    _id: '12',
    name: 'Floating Islands',
    imageUrl: 'https://azurefunctionsapp2022060.blob.core.windows.net/cyoa/islands_12.jpg',
    prompt: 'a magical realm of floating islands connected by vine bridges',
  },
  {
    _id: '13',
    name: 'Post-Apocalyptic Wasteland',
    imageUrl: 'https://azurefunctionsapp2022060.blob.core.windows.net/cyoa/wasteland_13.jpg',
    prompt: 'a barren post-apocalyptic wasteland with ruined cities',
  },
  {
    _id: '14',
    name: 'Steampunk City',
    imageUrl: 'https://azurefunctionsapp2022060.blob.core.windows.net/cyoa/steampunkcity_14.jpg',
    prompt: 'a steampunk city powered by gears and steam engines',
  },
  {
    _id: '15',
    name: 'Volcanic Island',
    imageUrl: 'https://azurefunctionsapp2022060.blob.core.windows.net/cyoa/volcano_15.jpg',
    prompt: 'a volatile volcanic island with lava flows and ash-filled skies',
  },
  {
    _id: '16',
    name: 'Sky City',
    imageUrl: 'https://azurefunctionsapp2022060.blob.core.windows.net/cyoa/cloudcity_16.jpg',
    prompt: 'a futuristic city suspended among the clouds',
  },
  {
    _id: '17',
    name: 'Ancient Temple',
    imageUrl: 'https://azurefunctionsapp2022060.blob.core.windows.net/cyoa/temple_17.jpg',
    prompt: 'an ancient temple filled with traps and forgotten deities',
  },
  {
    _id: '18',
    name: 'Swamp',
    imageUrl: 'https://azurefunctionsapp2022060.blob.core.windows.net/cyoa/swamp_18.jpg',
    prompt: 'a murky swamp with twisted trees and hidden dangers',
  },
  {
    _id: '19',
    name: 'Alien Planet',
    imageUrl: 'https://azurefunctionsapp2022060.blob.core.windows.net/cyoa/alienplanet_19.jpg',
    prompt: 'a strange alien planet with bizarre flora and fauna',
  },
  {
    _id: '20',
    name: 'Pirate Cove',
    imageUrl: 'https://azurefunctionsapp2022060.blob.core.windows.net/cyoa/piratecove_20.jpg',
    prompt: 'a hidden pirate cove with docked ships and buried treasure',
  },
];
