import { PlotOption } from '@/apps/cyoa/components/inputs/plot/PlotSelect';

export const childrensPlots: PlotOption[] = [
  { value: 'RANDOM', label: 'Random' },
  { value: 'Self_Discovery', label: 'A journey of self-discovery' },
  { value: 'New_Friend', label: 'Meeting a new friend' },
  { value: 'Lost_And_Found', label: 'Losing and finding something precious' },
  { value: 'Magical_Discovery', label: 'Discovering a magical world or object' },
  { value: 'Overcoming_Monster', label: 'Overcoming a big, scary challenge' },
  { value: 'Mischief_Maker', label: 'A mischievous character causing trouble' },
  { value: 'Family_Fixer', label: 'Fixing a family problem' },
  { value: 'Animal_Hero', label: 'An animal hero saving the day' },
  { value: 'Big_Move', label: 'Adapting to a big change' },
  { value: 'Imagination_Unleashed', label: 'Imagination coming to life' },
  { value: 'Secret_Hideout', label: 'Finding a secret hideout' },
  { value: 'Brave_Helper', label: 'A brave little helper stepping up' },
  { value: 'Time_Mix_Up', label: 'A mix-up in time' },
  { value: 'Lost_Voice', label: 'Finding a new way to be heard' },
  { value: 'Unexpected_Gift', label: 'Receiving an unexpected gift' },
  { value: 'Rival_Ally', label: 'Turning a rival into an ally' },
  { value: 'Weather_Whisperer', label: 'Controlling the weather' },
  { value: 'Tiny_World', label: 'Exploring a tiny world' },
  { value: 'Festival_Fiasco', label: 'Saving a festival from disaster' },
  { value: 'Dream_Weaver', label: 'Dreams shaping reality' },
];
